-- 🚀 AI Social Media Manager — Multi-Company Supabase Database Schema
-- Copy and paste this entire script into your Supabase project's SQL Editor (under "SQL Editor" -> "New query") and click RUN.
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / IF EXISTS guards).

-- ────────────────────────────────────────────────────────
-- 1. SYSTEM SETTINGS TABLE (operator-level config: Gemini key + dashboard password)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.system_settings (
    id text NOT NULL PRIMARY KEY,
    gemini_api_key text,
    dashboard_password_hash text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.system_settings;
CREATE POLICY "Allow all access to anon" ON public.system_settings FOR ALL TO anon USING (true) WITH CHECK (true);

ALTER TABLE public.system_settings ADD COLUMN IF NOT EXISTS dashboard_password_hash text;


-- ────────────────────────────────────────────────────────
-- 2. COMPANIES TABLE (one row per client/brand managed in the dashboard)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.companies (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    slug text UNIQUE NOT NULL,
    name text NOT NULL,
    industry text,
    business_context text,
    target_audience text,
    brand_voice text,
    content_pillars jsonb DEFAULT '[]'::jsonb,
    cta_text text,
    best_times jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.companies;
CREATE POLICY "Allow all access to anon" ON public.companies FOR ALL TO anon USING (true) WITH CHECK (true);

-- Seed a "New Gen Studios" company from the tool's original hardcoded brand context.
-- ON CONFLICT (slug) means this is safe to re-run and will not duplicate.
INSERT INTO public.companies (slug, name, industry, business_context, target_audience, brand_voice, content_pillars, cta_text, best_times)
VALUES (
    'new-gen-studios',
    'New Gen Studios',
    'AI Creative Agency (Jewellery & Fashion)',
    'New Gen Studios is an AI-powered creative agency based in Surat, India. We create luxury product photoshoots & cinematic Instagram Reels using AI. No models. No studios. No logistics. Clients send simple product photos and we deliver luxury visuals in 24-72 hours at 10x lower cost.',
    'Jewellery brands (gold, silver, handmade, luxury), Fashion & saree brands, Etsy sellers / Shopify store owners located in US, UK, UAE, Australia with 1K-100K followers. Pain points: expensive photoshoots, low-quality product photos, poor Instagram engagement, need premium branding without high cost.',
    'Premium, modern, disruptive, not corporate. Conversational, bold, slightly provocative. Focus on pain -> shift -> outcome -> soft sell. Avoid generic marketing tone.',
    '["Before/After transformation", "Educational (How AI shoots work)", "Client result / testimonial", "Trending Reel / viral hook", "Free sample offer / CTA", "Behind-the-scenes AI process", "Product showcase (jewellery)", "Product showcase (saree/fashion)", "Myth-busting post", "POV / relatable brand owner content"]'::jsonb,
    'DM us "SAMPLE" to get a FREE AI photoshoot of your product 🤍',
    '[["Tuesday", "11:00 AM IST (7:30 AM CEST / 6:30 AM GMT)"], ["Thursday", "07:00 PM IST (3:30 PM CEST / 2:30 PM GMT)"], ["Friday", "12:00 PM IST (8:30 AM CEST / 7:30 AM GMT)"], ["Saturday", "10:00 AM IST (6:30 AM CEST / 5:30 AM GMT)"], ["Sunday", "06:00 PM IST (2:30 PM CEST / 1:30 PM GMT)"]]'::jsonb
)
ON CONFLICT (slug) DO NOTHING;


-- ────────────────────────────────────────────────────────
-- 3. PLATFORM CONNECTIONS TABLE (per-company, per-platform credentials/tokens)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.platform_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    platform text NOT NULL CHECK (platform IN ('instagram', 'facebook', 'linkedin', 'google_business')),
    auth_type text NOT NULL DEFAULT 'password' CHECK (auth_type IN ('password', 'oauth')),
    credentials jsonb DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'connected',
    connected_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (company_id, platform)
);

ALTER TABLE public.platform_connections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.platform_connections;
CREATE POLICY "Allow all access to anon" ON public.platform_connections FOR ALL TO anon USING (true) WITH CHECK (true);

-- Carry forward any pre-existing single-tenant Instagram credentials (older installs stored
-- them on system_settings) into platform_connections for the seeded company, before that
-- legacy column is dropped below. No-op on fresh installs where the columns never existed.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='system_settings' AND column_name='instagram_username') THEN
        INSERT INTO public.platform_connections (company_id, platform, auth_type, credentials, status)
        SELECT
            (SELECT id FROM public.companies WHERE slug = 'new-gen-studios'),
            'instagram',
            'password',
            jsonb_build_object('username', s.instagram_username, 'password', s.instagram_password),
            'connected'
        FROM public.system_settings s
        WHERE s.id = 'default' AND s.instagram_username IS NOT NULL
        ON CONFLICT (company_id, platform) DO NOTHING;
    END IF;
END $$;

ALTER TABLE public.system_settings DROP COLUMN IF EXISTS instagram_username;
ALTER TABLE public.system_settings DROP COLUMN IF EXISTS instagram_password;


-- ────────────────────────────────────────────────────────
-- 4. POSTS HISTORY TABLE (tracks historical posts per company/platform to prevent repetition)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.posts_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE,
    platform text NOT NULL DEFAULT 'instagram',
    date text,
    post_type text,
    idea_summary text,
    reel_or_static text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.posts_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.posts_history;
CREATE POLICY "Allow all access to anon" ON public.posts_history FOR ALL TO anon USING (true) WITH CHECK (true);

ALTER TABLE public.posts_history ADD COLUMN IF NOT EXISTS company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.posts_history ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'instagram';

UPDATE public.posts_history
SET company_id = (SELECT id FROM public.companies WHERE slug = 'new-gen-studios')
WHERE company_id IS NULL;


-- ────────────────────────────────────────────────────────
-- 5. CURRENT CALENDAR TABLE (active generated calendar entries per company/platform)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.current_calendar (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE,
    platform text NOT NULL DEFAULT 'instagram',
    post_number bigint,
    date text,
    day text,
    time text,
    post_type text,
    reel_or_static text,
    hook text,
    caption text,
    hashtags text,
    image_prompt text,
    cta text,
    notes_for_creator text,
    is_done boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.current_calendar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.current_calendar;
CREATE POLICY "Allow all access to anon" ON public.current_calendar FOR ALL TO anon USING (true) WITH CHECK (true);

ALTER TABLE public.current_calendar ADD COLUMN IF NOT EXISTS is_done boolean DEFAULT false;
ALTER TABLE public.current_calendar ADD COLUMN IF NOT EXISTS company_id uuid REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.current_calendar ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'instagram';

UPDATE public.current_calendar
SET company_id = (SELECT id FROM public.companies WHERE slug = 'new-gen-studios')
WHERE company_id IS NULL;
