-- 🚀 New Gen Studios — Supabase Database Schema Setup
-- Copy and paste this entire script into your Supabase project's SQL Editor (under "SQL Editor" -> "New query") and click RUN.

-- ────────────────────────────────────────────────────────
-- 1. SYSTEM SETTINGS TABLE (Stores Gemini API keys & Instagram credentials)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.system_settings (
    id text NOT NULL PRIMARY KEY,
    gemini_api_key text,
    instagram_username text,
    instagram_password text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and create policy for full public REST API (anon) access
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.system_settings;
CREATE POLICY "Allow all access to anon" ON public.system_settings FOR ALL TO anon USING (true) WITH CHECK (true);


-- ────────────────────────────────────────────────────────
-- 2. POSTS HISTORY TABLE (Tracks historical posts to prevent strategy repetition)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.posts_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text,
    post_type text,
    idea_summary text,
    reel_or_static text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and create policy for full public REST API (anon) access
ALTER TABLE public.posts_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.posts_history;
CREATE POLICY "Allow all access to anon" ON public.posts_history FOR ALL TO anon USING (true) WITH CHECK (true);


-- ────────────────────────────────────────────────────────
-- 3. CURRENT CALENDAR TABLE (Stores active generated calendars)
-- ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.current_calendar (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_number bigint,
    date text,
    day text,
    time text,
    post_type text,
    reel_or_static text,
    hook text,
    caption text,
    hashtags text,
    image_prompt text,
    cta text,
    notes_for_creator text,
    is_done boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and create policy for full public REST API (anon) access
ALTER TABLE public.current_calendar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.current_calendar;
CREATE POLICY "Allow all access to anon" ON public.current_calendar FOR ALL TO anon USING (true) WITH CHECK (true);

-- ────────────────────────────────────────────────────────
-- MIGRATION: Run this single line if you already created the tables previously:
-- ALTER TABLE public.current_calendar ADD COLUMN IF NOT EXISTS is_done boolean DEFAULT false;
-- ────────────────────────────────────────────────────────
