-- 🔬 AI Social Media Manager — Schema additions: Deep Research + Live Trend Monitoring
-- Run this AFTER your existing schema.sql (or with it — every statement is idempotent).
-- Copy and paste into your Supabase project's SQL Editor and click RUN.

-- ──────────────────────────────────────────────────────────
-- 1. COMPANIES: new columns for deep research
-- ──────────────────────────────────────────────────────────
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS website_url text DEFAULT '';
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS auto_research boolean DEFAULT false;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS last_researched_at timestamp with time zone;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS research_summary text DEFAULT '';
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS research_sources jsonb DEFAULT '[]'::jsonb;


-- ──────────────────────────────────────────────────────────
-- 2. TREND CACHE TABLE (per company + platform, 6-hour TTL enforced in app code)
-- ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.trend_cache (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    platform text NOT NULL,
    trends jsonb DEFAULT '[]'::jsonb,
    sources jsonb DEFAULT '[]'::jsonb,
    fetched_at timestamp with time zone,
    UNIQUE (company_id, platform)
);

ALTER TABLE public.trend_cache ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to anon" ON public.trend_cache;
CREATE POLICY "Allow all access to anon" ON public.trend_cache FOR ALL TO anon USING (true) WITH CHECK (true);


-- ──────────────────────────────────────────────────────────
-- 3. CURRENT_CALENDAR: new columns for script + editing style
--    (generate_posts() now emits these per post; without these columns,
--    saving/exporting a calendar to Supabase would fail once Supabase is connected)
-- ──────────────────────────────────────────────────────────
ALTER TABLE public.current_calendar ADD COLUMN IF NOT EXISTS script text DEFAULT '';
ALTER TABLE public.current_calendar ADD COLUMN IF NOT EXISTS editing_style text DEFAULT '';
